"""End-to-end run: simulate -> value -> estimate causal effects -> optimize -> plot -> report.

    python run_all.py                 # full run (~1-2 min on a laptop)
    python run_all.py --quick         # smaller sample, fewer bootstrap draws
    python run_all.py --seed 11       # different random world, same structure
"""
from __future__ import annotations

import argparse
import time
from pathlib import Path

import numpy as np
import pandas as pd

from offerpad_simulator.config import SimConfig
from offerpad_simulator.simulate import observed_columns, simulate, simulate_history, true_accept_prob
from offerpad_simulator.valuation import evaluate
from offerpad_simulator.causal import (seller_side_estimates, buyer_side_estimates, segment_iv, hte_causal_forest,
                          true_seller_effect)
from offerpad_simulator.optimize import (seller_policy_curves, buyer_policy_curves, three_percent_cut_table,
                            volume_constrained_frontier, theta_uncertainty)
from offerpad_simulator.seller_psych import self_appreciation_summary
from offerpad_simulator import viz

HERE = Path(__file__).parent
OUT, FIG, DATA = HERE / "outputs", HERE / "outputs" / "figures", HERE / "outputs" / "data"


def md(df: pd.DataFrame, fmt=".3f") -> str:
    return df.to_markdown(index=False, floatfmt=fmt)


def main(quick: bool = False, seed: int = 7) -> None:
    t0 = time.time()
    cfg = SimConfig(seed=seed, n_leads=25_000 if quick else 60_000)
    log = lambda m: print(f"[{time.time() - t0:5.1f}s] {m}", flush=True)

    # ---------------------------------------------------------------- 0 data
    df, ovm, hist = simulate(cfg, return_ovm=True)
    DATA.mkdir(parents=True, exist_ok=True)
    df.to_parquet(DATA / "leads_full_with_truth.parquet")
    df[observed_columns(df)].to_parquet(DATA / "leads_observed.parquet")
    df.sample(2000, random_state=0).to_csv(DATA / "leads_sample_2k.csv", index=False)
    log(f"simulated {len(df):,} offers, acceptance {df['accept'].mean():.1%}")

    # ---------------------------------------------------------------- 1 valuation
    test = simulate_history(SimConfig(n_history=10_000), np.random.default_rng(seed + 100))
    val = evaluate(ovm, test)
    viz.fig_valuation(ovm, test, FIG)
    log(f"OVM median APE {val['gbm_median_ape']:.2%}")

    # ---------------------------------------------------------------- 2 causal
    viz.fig_confounding(df, FIG)
    seller = seller_side_estimates(df, n_boot=5 if quick else 20, fee=cfg.fee)
    viz.fig_estimators(seller, FIG, "Seller side: effect of +1pp spread on acceptance", "fig03_seller_estimators.png",
                       "Δ acceptance (pp) per +1pp spread  (95% CI)")
    buyer = buyer_side_estimates(df, cfg)
    viz.fig_estimators(buyer.iloc[:2], FIG, "Buyer side: effect of +1% list price on P(sold ≤ 60d)",
                       "fig03b_buyer_estimators.png", "Δ P(sold ≤ 60d) (pp) per +1% list price  (95% CI)")
    viz.fig_first_stage(df, FIG, cfg.v2_day)
    seg = segment_iv(df)
    forest = hte_causal_forest(df, seed=seed)
    viz.fig_hte(seg, forest, FIG)
    log("causal estimates done")

    # ---------------------------------------------------------------- 3 self-appreciation
    sa = self_appreciation_summary(df)
    viz.fig_self_appreciation(sa, FIG)

    # ---------------------------------------------------------------- 4 optimization
    sres = seller_policy_curves(df, cfg=cfg)
    viz.fig_seller_opt(sres, FIG)
    bres = buyer_policy_curves(df, cfg=cfg)
    viz.fig_buyer_opt(bres, FIG)
    cut = three_percent_cut_table(bres["curves"])
    fr = volume_constrained_frontier(df, sres["acc_cf"], sres["mm_sel"], cfg=cfg)
    f = fr["frontier"]
    base_vol = f.loc[0, "seg_pred_volume"]
    target = base_vol * 1.30
    hit = f[f["seg_pred_volume"] >= target].iloc[0]
    viz.fig_frontier(fr, target, FIG)
    unc = theta_uncertainty(bres["iv"])
    viz.fig_uncertainty(unc, FIG)
    log("optimization done")

    # ---------------------------------------------------------------- 5 report
    t_seller = true_seller_effect(df, fee=cfg.fee)
    three_pct_offer = (
        df["true_p_accept"].mean(),
        float(np.mean(true_accept_prob(df, price_mult=1.03, fee=cfg.fee))),
    )
    lines = [
        "# Results (auto-generated by `run_all.py`)",
        f"\nseed = {seed}, offers = {len(df):,}, acceptance = {df['accept'].mean():.1%}, homes bought = {int(df['accept'].sum()):,}",
        f"\nPortfolio at current policy: gross margin {df['gross_profit'].sum() / df['sale_price'].sum():.1%}, "
        f"contribution margin {df['contribution'].sum() / df['sale_price'].sum():.1%}, "
        f"median DOM {df['dom'].median():.0f} days",
        "\n## 1. Valuation model (OVM)",
        md(pd.DataFrame([{k: v for k, v in val.items() if not isinstance(v, list)}]), ".4f"),
        f"\nMedian |log error| by predicted-uncertainty quintile: {val['abs_err_by_uncertainty_quintile']}",
        "\n![valuation](figures/fig01_valuation.png)",
        "\n## 2. Causal effect of price on conversion",
        "\n### Seller side — +1pp spread → acceptance (pp)",
        md(seller[["estimator", "estimate", "se", "truth", "bias", "note"]], ".2f"),
        "\n![confounding](figures/fig02_confounding.png)\n\n![seller estimators](figures/fig03_seller_estimators.png)",
        "\n![first stage](figures/fig04_first_stage.png)",
        "\n### Buyer side — +1% list price → P(sold ≤ 60d) (pp); log DOM elasticity θ/100",
        md(buyer[["estimator", "estimate", "se", "truth", "bias", "note"]], ".3f"),
        "\n![buyer estimators](figures/fig03b_buyer_estimators.png)",
        "\n### Heterogeneity (+1pp spread, pp acceptance)",
        md(seg.merge(forest[["urgency", "has_agent_quote", "cate_hat"]], on=["urgency", "has_agent_quote"]), ".2f"),
        "\n![hte](figures/fig05_hte.png)",
        "\n## 3. Customer self-appreciation",
        f"\nSellers' stated value exceeds the OVM by {sa['base_premium']:.1%} + {sa['passthrough']:.2f} × trailing market HPA "
        f"(true: {cfg.self_apprec_base:.0%} + {cfg.self_apprec_hpa_passthrough:.1f} × HPA).",
        f"\nAdding the stated value to the acceptance model lifts pseudo-R² from {sa['pseudo_r2_without']:.3f} to {sa['pseudo_r2_with']:.3f}.",
        "\nOVM error log(true/OVM) by outcome:\n", sa["adverse_selection"].round(4).to_markdown(),
        "\n![self appreciation](figures/fig06_self_appreciation.png)",
        "\n## 4. Worked examples",
        f"\n**Seller side, offer 3% higher:** true acceptance {three_pct_offer[0]:.1%} → {three_pct_offer[1]:.1%}. "
        f"Linear causal estimate: {seller.set_index('estimator').loc['2SLS: randomized spread arm', 'estimate']:.2f} pp per pp of spread "
        f"(truth {t_seller:.2f}).",
        "\n**Buyer side, list 3% lower (per bought home):**\n",
        cut.round(2).reset_index().to_markdown(index=False),
        "\n![3% cut](figures/fig08_buyer_3pct_cut.png)",
        "\n## 5. Optimization",
        "\n### Seller side: spread change that maximizes E[contribution] per offer",
        md(sres["optimum"], ".2f"),
        f"\nWinner's-curse slope c = {sres['winners_curse_slope']:.3f} (se {sres['winners_curse_se']:.3f}): "
        "each extra point of spread adds only (1 + c) points of margin on the accepted pool.",
        "\n![seller opt](figures/fig07_seller_optimization.png)",
        "\n### Buyer side: list-price multiplier that maximizes E[contribution] per home",
        md(bres["optimum"], ".3f"),
        f"\nθ̂ = {bres['iv'].theta:.2f} (se {bres['iv'].theta_se:.2f}; truth {cfg.theta_price}),  naive θ̂ = {bres['naive'].theta:.2f}. "
        f"Robust optimum under (θ, η) uncertainty: {unc['rho_robust']:.3f}; 90% of draws in "
        f"[{np.percentile(unc['rho_star_draws'], 5):.3f}, {np.percentile(unc['rho_star_draws'], 95):.3f}].",
        "\n![uncertainty](figures/fig10_elasticity_uncertainty.png)",
        "\n### Volume target (+30% acquisitions vs margin-maximizing policy)",
        f"\nShadow price needed: λ ≈ ${hit['shadow_price']:,.0f} of margin per extra acquisition. "
        f"Segment-specific spreads (true): volume {hit['seg_true_volume']:.3f}/offer, contribution ${hit['seg_true_contrib']:,.0f}/offer. "
        f"Chosen spread changes (pp): " + ", ".join(f"{s}: {hit['delta_' + s]:+.2f}" for s in fr["segments"]),
        "\n![frontier](figures/fig09_margin_volume_frontier.png)",
    ]
    (OUT / "results.md").write_text("\n".join(lines), encoding="utf-8")
    seller.to_csv(OUT / "seller_estimates.csv", index=False)
    buyer.to_csv(OUT / "buyer_estimates.csv", index=False)
    log(f"wrote {OUT / 'results.md'}")
    print("\n", seller[["estimator", "estimate", "truth"]].round(2).to_string(index=False))
    print("\n", bres["optimum"].round(3).to_string(index=False))


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--quick", action="store_true")
    ap.add_argument("--seed", type=int, default=7)
    a = ap.parse_args()
    main(quick=a.quick, seed=a.seed)
